name: Unit Testing Execution
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: "true"
          submodules: recursive
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - name: Setup Just
        uses: extractions/setup-just@v1
      - name: Execute tests
        run: just test
