name: Run Tests
on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup LuaJIT
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - name: Setup Just
        uses: extractions/setup-just@v1
      - name: Execute tests
        run: just test
